### ISSUE TITLE
graphviz plugin does nothing

### ISSUE THREAD

**Issue by kilmarnock** [gephi/gephi-plugins#177]
Hi!
I am using gephi 0.9.2 with graphviz 2.38.0-12 on ubuntu 16.04.
When I press "start" for doing the graphiv layout, nothing happens. 
If I change the name of the binary to a non existing file, a message pops up (no such file).
The command line shows nothing.
The nodes do not move.
Thank you

**Comment by eduramiba** [comment]
Does it show any exception in the logs or the bottom right corner of gephi?

**Comment by kilmarnock** [comment]
No, there is no reaction
-on the gui
-on the command line
-in  .gephi/0.9.2/dev/var/log/messages.log
after pressing start. 

On boot, the log shows:

>
....
 Diagnostic information
Input arguments:
	-Djdk.home=/usr/lib/jvm/java-8-oracle
	-Dnetbeans.running.environment=gnome
	-Dnetbeans.dirs=/usr/local/gephi-0.9.2/platform:/usr/local/gephi-0.9.2/gephi:
	-Dnetbeans.home=/usr/local/gephi-0.9.2/platform
	-Xms64m
	-Xmx512m
	-Xverify:none
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-DaddExports:java.desktop/sun.awt=ALL-UNNAMED
	-DaddExports:java.base/jdk.internal.jrtfs=ALL-UNNAMED
	-DaddExports:java.desktop/java.awt.peer=ALL-UNNAMED
	-DaddExports:java.desktop/com.sun.beans.editors=ALL-UNNAMED
	-DaddExports:java.desktop/sun.awt.im=ALL-UNNAMED
	-DaddExports:java.desktop/com.sun.java.swing.plaf.gtk=ALL-UNNAMED
	-DaddExports:java.management/sun.management=ALL-UNNAMED
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=/home/homer/.gephi/0.9.2/dev/var/log/heapdump.hprof
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 64,0MB maximum 455,5MB
Non heap memory usage: initial 2,4MB maximum -1b
Garbage collector: PS Scavenge (Collections=7 Total time spent=0s)
Garbage collector: PS MarkSweep (Collections=2 Total time spent=0s)
Classes: loaded=6684 total loaded=6684 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 16.774.721.536
INFO [null]: Gesamter physischer Speicher 16.774.721.536
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/View/ marked with the position attribute: [org-netbeans-core-windows-actions-ToggleFullScreenAction.instance], but some are: [ToggleFullScreenAction.shadow]
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url
INFO [org.netbeans.core.ui.focus]: External Changes Refresh on focus gain disabled
WARNING: Error: <stdin>: syntax error in line 42 near '/'

**Comment by kilmarnock** [comment]
Tried a fresh install, updated, installed graphviz plugin only, no success.

**Comment by PatrickMassot** [comment]
I would be nice to have news about this issue. The only graphs I've been able to layout using this plugin are graphs generated at random inside gephi.

**Comment by Noricc** [comment]
I also wanted to use the graphviz plugin, same behavior as @PatrickMassot mentioned.

**Comment by ZwergNaseXXL** [comment]
After trying various remedies which led to various errors or nothing happening, I came across @PatrickMassot 's comment, which set me on the right track. If internally generated graphs work, but imported ones don't, it must be something in the XML, right? 

Looking in the output window, the GraphViz plugin generates warnings like this:
`[WARNING] Cannot find nodeid "2" from matcher group "	2	 [height=0.5,
		pos="297,146.08",
		width=0.75]" `

Then looking at @chunky 's source at [https://github.com/chunky/gephi-plugins/blob/master/modules/GraphvizLayout/src/main/java/org/icculus/chunky/gephigraphviz/GraphvizLayout.java](https://github.com/chunky/gephi-plugins/blob/master/modules/GraphvizLayout/src/main/java/org/icculus/chunky/gephigraphviz/GraphvizLayout.java) , I followed a hunch and removed the attribute `idtype="integer"` from the `graph` element in my file. Et voila, it works now!

Easy enough as a workaround, but still worth fixing, since using `idtype="integer"` is recommended for performance reasons. Unfortunately, @chunky hasn't touched his plugin since the initial release in 2016.
