### ISSUE TITLE
gephi-plugin-parent not updated in Maven Central

### ISSUE THREAD

**Issue by cbartosiak** [gephi/gephi-plugins#178]
Hi,

I'm currently working on migrating **Complex Generators** plugin... and I've stumbled across the problem that `gephi-plugin-parent` artifact is not updated in _Maven Central_. Currently `0.9.1` version is available. I could install `0.9.2` in my local Maven, but it looks like it should be available in the central repository anyway.

**Comment by eduramiba** [comment]
I don't think we deployed that to maven central, but it's only used as a means to build all plugins in the same way by forking our `master` branch. If you follow the steps explained in the readme you should be able to build your plugin without problems, since your plugin branch will have a copy of that parent.

**Comment by cbartosiak** [comment]
Indeed, I can build it, but IDE (IntelliJ) keeps showing the configuration is not correct. It's not a big deal, but it's confusing from the Maven build perspective. Maybe it's better to keep this issue open and mark as "feature request" to make the configuration more Maven friendly? What do you think?

**Comment by eduramiba** [comment]
Sure, reopening!

**Comment by mbastian** [comment]
Thanks for the report. For some reasons we missed the `0.9.2` version. It's corrected now. And we've also automated that so that every new version is automatically released to Maven central. That's also the case for the 0.9.3 version we've just released: https://repo.maven.apache.org/maven2/org/gephi/gephi-plugin-parent/0.9.3/
