### ISSUE TITLE
Leiden algo: many communities with a single node

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi-plugins#203]
The algo finds many communities which are made of just one node, even when these nodes are not isolated. That is not very useful and actually on large networks, this creates hundreds of communities which make the results impractical to process further.

**Comment by eduramiba** [comment]
Hi, when testing it, I found that the resolution parameter must be tweaked for every network and is quite sensitive, so you must test a few numbers until you find one that suits your network.

@vtraag can you provide some help?

**Comment by vtraag** [comment]
Ah, @seinecle, I thought the problem was that it slowed down Gephi?

The single community nodes may simply not fit anywhere else better. Indeed this will be affected by the resolution parameter. Louvain may leave these nodes in larger communities, while they shouldn't.

@eduramiba, is it convenient to keep this issue here? Or is vtraag/gephi-leiden-plugin more suitable for tracking issues around this specific plugin?

**Comment by seinecle** [comment]
Hey!
I've written the issue here as I could not see the issues in the menu of vtraag/gephi-leiden-plugin, but I'll check again.
There were two issues: lots of communities with jus one node, and slowness of treatment after the report popup.
Maybe that it could be left to the user to delete / not create communities that have a member count < n?

**Comment by vtraag** [comment]
Moved to https://github.com/vtraag/gephi-leiden-plugin/issues/2, @eduramiba, you can close this one.
