### ISSUE TITLE
[neo4j-plugin] REST Support

### ISSUE THREAD

**Issue by techdragon** [gephi/gephi-plugins#52]
Can we explore getting the plugin to work with the REST API for those of us who are doing things like running with a server cluster and don't have a single unified copy of the DB

**Comment by sim51** [comment]
Since Neo4j 3.X the good way to connect to a Neo4j server is to use the bolt protocol with the provided driver.
Bolt handles all the way to connect to a cluster and do the routing itself.

I'm not sure there is still a need for this feature with the new neo4j plugin (see #263), so I'm closing this ticket.
